Add Customers CRUD
juanzitelli/caldar-platform pull request #8
Opened 2021-09-07 04:25 UTC by EduardoCitelli

# Feature

The feature's title

# Description

Describe your feature including why is it relevant and describe future steps.

# Changelog

- Update 1
- Update 2
- Update 3

# Screenshots

Add some cool pictures of your work (if applicable) 📷

2021-09-08 23:39 UTC, juanzitelli requested changes
Nice job! 👏🏻 Still, please take a look at the comments I left below, you can commit them directly in Github without actually going back to VSCode!

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +  let response = getDataCustomers();
Let's try to use `const` when a variable is not re-assigned

```suggestion
  const response = getDataCustomers();
```

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +  let customers = getDataCustomers();
Let's try to use `const` when a variable is not re-assigned
```suggestion
  const customers = getDataCustomers();
```

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +function saveData(list: Customer[]) {
Let's try to use arrow functions when possible! To keep consistency
```suggestion
const saveData = (list: Customer[]) => {
```

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +  let response: Customer[] = JSON.parse(data);
```suggestion
  const data = fs.readFileSync(customersDataFilePath, "utf-8");

  const response: Customer[] = JSON.parse(data);
```

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +  let list = !query.type
Let's try to use `const` when a variable is not re-assigned
```suggestion
  const list = !query.type
```

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +  let existCustomer = customers.some((x) => x.id === updatedCustomer.id);
Replace `let` for `const` and rename `existsCustomer` boolean variable for a better spelling

```suggestion
  const customers = getDataCustomers();

  const customerExists = customers.some((x) => x.id === updatedCustomer.id);
```

2021-09-08 23:39 UTC, juanzitelli commented on services/caldar-api/src/controllers/customer-controller.ts
> +  if (!existCustomer) {
Renamed variable for a better spelling
```suggestion
  if (!customerExists) {
```

2021-09-08 23:39 UTC, juanzitelli commented on .gitignore
> +/.vs
If with this line you were trying to ignore .vscode, please don't. I intentionally added a `.vscode` extension recommendation file so the IDE would suggest you install a REST client which I think it's nice!.
```suggestion
```

2021-09-08 23:39 UTC, juanzitelli commented on packages/caldar-types/src/enums/customer-type.ts
> +  PRIVATE,
When declare other `enums` (i.e. `CustomerRoutes`) we use the "Pascal" casing convention, what do you think about changing this one for it to respect that convention?
```suggestion
  Construction = 1,
  Private,
```

2021-09-09 01:53 UTC, EduardoCitelli commented on .gitignore
> +/.vs
this ignore si for de IDE visual studio 2019

2021-09-09 02:04 UTC, juanzitelli approved these changes
Nice job 👏🏻

2021-09-09 02:04 UTC, merged